pipeline {
  agent {
          docker {
              image 'maven:3.8.8-eclipse-temurin-21'
          }
      }

    

    environment {
        MAVEN_OPTS = "-Dmaven.compiler.source=21 -Dmaven.compiler.target=21"
    }

    stages {
        stage('Build') {
            steps {
                dir('product-service') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('product-service') {
                    sh 'mvn test'
                }
            }
        }
    }

    post {
        success {
            echo "✅ Build & Test for product-service completed using Java 21"
        }
        failure {
            echo "❌ Build or tests failed"
        }
    }
}
